### ISSUE TITLE
The new _initialize_consent function causes error when downloading YouTube videos using a cookies file

### ISSUE THREAD

**Issue by apaloma** [ytdl-org/youtube-dl#28666]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2021.04.01**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: [u'--output', u'History/%(upload_date)s - %(id)s - %(title)s - %(view_count)s views.%(ext)s', u'-f', u'bestvideo+bestaudio/best', u'-ciw', u'-v', u'--embed-subs', u'--all-subs', u'--add-metadata', u'--restrict-filenames', u'--write-all-thumbnails', u'--write-info-json', u'--download-archive', u'history.arc.txt', u'--force-ipv4', u'--cookies', u'cookies.txt', u'--match-filter', u'!is_live', u'https://www.youtube.com/feed/history']
[debug] Encodings: locale UTF-8, fs UTF-8, out UTF-8, pref UTF-8
[debug] youtube-dl version 2021.04.01
[debug] Python version 2.7.12 (CPython) - Linux-4.4.0-206-generic-x86_64-with-Ubuntu-16.04-xenial
[debug] exe versions: ffmpeg 4.3.1-0york0, ffprobe 4.3.1-0york0, rtmpdump 2.4
[debug] Proxy map: {}
ERROR: 'unicode' object has no attribute 'items'
Traceback (most recent call last):
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 806, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/bin/youtube-dl/youtube_dl/YoutubeDL.py", line 827, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 533, in extract
    self.initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 437, in initialize
    self._real_initialize()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 268, in _real_initialize
    self._initialize_consent()
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/youtube.py", line 253, in _initialize_consent
    cookies = self._get_cookies('https://www.youtube.com/')
  File "/usr/local/bin/youtube-dl/youtube_dl/extractor/common.py", line 2902, in _get_cookies
    return compat_cookies.SimpleCookie(req.get_header('Cookie'))
  File "/usr/lib/python2.7/Cookie.py", line 583, in __init__
    if input: self.load(input)
  File "/usr/lib/python2.7/Cookie.py", line 643, in load
    for k, v in rawdata.items():
AttributeError: 'unicode' object has no attribute 'items'

```

## Description

After updating youtube-dl to 2021.04.01, I can no longer download YouTube videos with the --cookies option. I have tried updating my cookies file.

I'm pretty sure the cause is @dstftw's fix in issue #28604

**Comment by kikuyan** [comment]
See #28640, #28652.

**Comment by Originalimoc** [comment]
Same problem, waiting for update.
